function params = import_google_form_extra(filename)
% params = import_google_form_extra('GroupThere_testInput_extra.csv')
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Zach/Drive/m_PDP_TW/GroupThere_testInput_extra.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/04/08 14:09:04

%% Initialize variables.
% filename = '/Users/Zach/Drive/m_PDP_TW/GroupThere_testInput_extra.csv';
delimiter = ',';
startRow = 2;

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,6]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using date
% format string.
try
    dates{5} = datetime(dataArray{5}, 'Format', 'hh:mm:ss a', 'InputFormat', 'hh:mm:ss a');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{5} = cellfun(@(x) x(2:end-1), dataArray{5}, 'UniformOutput', false);
        dates{5} = datetime(dataArray{5}, 'Format', 'hh:mm:ss a', 'InputFormat', 'hh:mm:ss a');
    catch
        dates{5} = repmat(datetime([NaN NaN NaN]), size(dataArray{5}));
    end
end

anyBlankDates = cellfun(@isempty, dataArray{5});
anyInvalidDates = isnan(dates{5}.Hour) - anyBlankDates;
dates = dates(:,5);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,6]);
rawCellColumns = raw(:, [1,3,4,7]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
Timestamp = rawCellColumns(:, 1);
EmailAddress = cell2mat(rawNumericColumns(:, 1));
Name = rawCellColumns(:, 2);
Address = rawCellColumns(:, 3);
leaveTime = dates{:, 1};
numSeats = cell2mat(rawNumericColumns(:, 2));
extra = rawCellColumns(:, 4);



%% Process leaveTime
leaveTime=datevec(leaveTime);
leaveTime = 60*leaveTime(:,4) + leaveTime(:,5);
leaveTime = leaveTime(1)-leaveTime;
leaveTime = leaveTime/60;

%% Process Extra
extra = double(strcmp(extra,'No'));

%% Save to struct
params.Emails = dataArray{2};
params.Name = Name;
params.Address = (dataArray{:, 4})';
params.NumberCarSeats = numSeats;
params.HoursAvailableforTransit = leaveTime;
params.extra = extra;
params.rawNumericColumns = rawNumericColumns;
params.rawCellColumns = rawCellColumns



end